### ISSUE TITLE
_get_kriging_matrix is very long for large datasets

### ISSUE THREAD

**Issue by alexisrosuel** [GeoStat-Framework/PyKrige#68] opened 2017-07-03 15:22 UTC
Hi again,

I just saw that the function '_get_kriging_matrix' is very very long (about 5-10 secs) when the training points size is about 10,000 or 15,000.

Do you know if a speed up would be possible ? For instance, I was thinking that as I specified in my model 'n_closed_points' = 100, computing the kriging matrix over the 100 nearest points would be sufficient ?

**Comment by rth** [comment] 2017-07-04 09:09
@alexisrosuel The bottleneck must be in the `cdist` and `variogram` calculations [in `_get_kriging_matrix`]( https://github.com/bsmurphy/PyKrige/blob/22c8a6955719168235b7f4d8b989b78575c12c82/pykrige/ok.py#L501) .  

Would this issue be related to a local variogram model discussed in https://github.com/bsmurphy/PyKrige/issues/41?

**Comment by alexisrosuel** [comment] 2017-07-04 11:57
Yes indeed, I was not sure yesterday, but it is clear now that this is the same issue

**Comment by basaks** [comment] 2017-07-04 18:34
@rth Yes, very much so. A local variogram model could help in this situation.
I am still looking to get some funding for that work.

**Comment by MuellerSeb** [comment] 2020-01-28 12:24
I would say the problem is, that even with ``n_closest_points`` given, the whole matrix is constructed. This should be only done for the points needed.

**Comment by MuellerSeb** [comment] 2020-04-05 10:26
This should be discussed in #143. Closing for now. Feel free to re-open or go on with discussion in the linked issue.

**Closed by MuellerSeb** 2020-04-05 10:26 UTC
Labels: Refactoring, enhancement
