### ISSUE TITLE
4D Ordinary Kriging?

### ISSUE THREAD

**Issue by ellawang44** [GeoStat-Framework/PyKrige#133] opened 2019-12-30 06:06 UTC
Hi, 

Is it possible to implement a 4D ordinary kriging object? I've had a look through the ok3d.py file but I'm not sure how to change the adjusted arrays to include another dimension. I'm aware that kriging is usually done in 2D or 3D but I have a specific 4D data set I'd like to use this on. 

Thanks

**Comment by MuellerSeb** [comment] 2020-01-26 21:15
The isotropic case shouldn't be to hard, since we only need the distance between points.
The problem is the characterization of rotation in higher dimensions, which is really non-trivial.

An implementation approach could include an N-dimensional implementation for isotropic variogram models.

**Comment by MuellerSeb** [comment] 2020-04-04 17:00
We will discuss this here: #138. Closing for now. Feel free to Re-open or (better) discuss in the linked issue.

**Closed as completed by MuellerSeb** 2020-04-04 17:00 UTC
Labels: enhancement, help wanted, new feature
